### ISSUE TITLE
Support for fine-tuning huggingface/mbart models

### ISSUE THREAD

**Issue by pdakwal** [xhluca/dl-translate#38]
Hi,

Is there any plan to also provide support for fine-tuning mbart models?

**Comment by nikhiljaiswal** [comment]
@pdakwal were u able to finetune mbart50? Can you please help?

**Comment by xhlulu** [comment]
@nikhiljaiswal Huggingface released a code snippet that shows you how to do the forward pass: https://huggingface.co/docs/transformers/model_doc/mbart#training-of-mbart50

You can easily do the backward pass using the regular pytorch approach:
```python
optimizer = optim.AdamW(model.parameters(), lr=0.0001)

#load input here
loss = model(**model_inputs, labels=labels).loss
loss.backward()
optimizer.step()
optimizer.zero_grad()

# continue here...
```

**Comment by xhluca** [comment]
Huggingface now has a tutorial for finetuning: https://huggingface.co/docs/transformers/tasks/translation

It's already very abstracted, so there's not a lot of value in further abstracting it as it would actually hurt the flexibility of the training process (as a lot of decisions need to be taken).
