### ISSUE TITLE
Cannot run with device = 'gpu' on Macbook M1 Pro

### ISSUE THREAD

**Issue by htnha** [xhluca/dl-translate#53]
I have tried to using gpu on Macbook 16inch M1 Pro, then I got this error: "AssertionError: Torch not compiled with CUDA enabled"

Please help!

**Comment by xhluca** [comment]
You can only use CUDA on Nvidia GPUs. For M-series macbooks, you will need to follow Macbook-specific instructions for pytorch (here's a good [starting point](https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/))
