### ISSUE TITLE
Unfortunately you can't offer this under MIT license

### ISSUE THREAD

**Issue by laelhalawani** [xhluca/dl-translate#66]
Hi, you can't redistribute the components in this package under MIT since this package uses NLLB, which is distributed under CC-BY-NC license. The reason is that the CC-BY-NC license restricts commercial use, whereas the MIT license is a permissive open-source license that allows commercial use.

**Comment by xhluca** [comment]
The code in this repository is distributed under MIT, and it does not depend on any code created by the NLLB team, nor does it distribute or derive from the weights published by the NLLB team under their license. If you believe a specific section of the code was taken from a library with a different license, please let me know which part and I will correct the license for that part.

This library is designed as an interface for specific models on Huggingface by offering abstractions and tools to make it easier to use those models, each of which has a license that is unrelated to the code in this repository. If you believe it would help end users choose a better model, I am happy to accept a PR that includes the link to relevant licenses for the supported model families in the readme.
